### ISSUE TITLE
Improve structure of GitHub repository

### ISSUE THREAD

**Issue by HowardCohl** [plato2000/NIST-misc#1]
CC: @physikerwelt 

@plato2000 

The structure of the plato2000/NIST-misc GitHub repository can be improved: 
- A src directory should be created which contains source files only, data files should be in a separate data folder. 
- The README.md file should follow standard structure describing the project, such as calling sequences, detailed description of what the project is, etc.

**Comment by plusparth** [comment]
Fixed structure in a785403, hopefully

**Comment by plusparth** [comment]
Added more to README in a4701d1
